apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-glob-configmap
data:
    {{ $currentScope := . }}
    {{ range $path, $_ :=  .Files.Glob  "**.conf" }}
        {{- with $currentScope}}
    {{ $path }}: | - 
            {{ .Files.Get $path | indent 4 }}
        {{- end }}
    {{ end }}
